/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Classes.Graphe;
import Classes.Paint;
import java.awt.Frame;
import javax.swing.JOptionPane;

public class Aréte_window extends javax.swing.JFrame {

    Paint paint;
    Graphe graphe;
    Frame frame1;

    public Aréte_window(Graphe graphe, Paint paint, int I, Frame frame) {
        this.paint = paint;
        this.graphe = graphe;
        this.i = I;
        frame1 = frame;

        initComponents();

    }

    private Aréte_window() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sommet1_txt = new javax.swing.JTextField();
        sommet2_txt = new javax.swing.JTextField();
        poids_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        déssiner_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shortest Path");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(60, 109, 245));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 109, 245));
        jLabel1.setText("Entrez le sommet 1:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 109, 245));
        jLabel2.setText("Entrez le sommet 2:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 50, 120, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 109, 245));
        jLabel3.setText("Entrez le poids:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 90, 90, 14);

        sommet1_txt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sommet1_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sommet1_txtKeyReleased(evt);
            }
        });
        jPanel2.add(sommet1_txt);
        sommet1_txt.setBounds(130, 10, 30, 20);

        sommet2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sommet2_txtActionPerformed(evt);
            }
        });
        sommet2_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sommet2_txtKeyReleased(evt);
            }
        });
        jPanel2.add(sommet2_txt);
        sommet2_txt.setBounds(130, 50, 30, 20);

        poids_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                poids_txtKeyReleased(evt);
            }
        });
        jPanel2.add(poids_txt);
        poids_txt.setBounds(130, 90, 30, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 180, 130);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nouvelle Aréte");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 20, 100, 15);

        déssiner_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        déssiner_btn.setForeground(new java.awt.Color(60, 109, 245));
        déssiner_btn.setText("Déssiner");
        déssiner_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                déssiner_btnActionPerformed(evt);
            }
        });
        jPanel1.add(déssiner_btn);
        déssiner_btn.setBounds(60, 190, 90, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sommet2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sommet2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sommet2_txtActionPerformed

    private void déssiner_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_déssiner_btnActionPerformed
        int x;
        int y;
        int taille;
        if (sommet1_txt.getText().length() < 1 || sommet2_txt.getText().length() < 1 || poids_txt.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Erreur.. Données manqauntes : ");
        } else {
            x = Integer.parseInt(sommet1_txt.getText());
            y = Integer.parseInt(sommet2_txt.getText());
            taille = Integer.parseInt(poids_txt.getText());

            if (x == y) {
                JOptionPane.showMessageDialog(null, "Erreur ... vous devez taper un autre sommet: " + y);
            } else if (x < 0 || x >= i || y < 0 || y >= i) {
                JOptionPane.showMessageDialog(null, "Erreur.. sommet non valide ");
            } else {
                graphe.setMatrice_adjacence(x, y, 1);
                graphe.setMatrice_adjacence(y, x, 1);
                graphe.setMatrice_Coefficients(x, y, taille);
                graphe.setMatrice_Coefficients(y, x, taille);
                sommet1_txt.setText(null);
                sommet2_txt.setText(null);
                poids_txt.setText(null);
                Paint.Paint_Line(Principal_Window.graphe_panel.getGraphics(), graphe.getCordX(x), graphe.getCordY(x), graphe.getCordX(y), graphe.getCordY(y), taille);

            }
        }
    }//GEN-LAST:event_déssiner_btnActionPerformed

    private void sommet1_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sommet1_txtKeyReleased
        String tem = new String(sommet1_txt.getText());
        StringBuffer tem2 = new StringBuffer();
        for (int j = 0; j < tem.length(); j++) {
            if (Character.isDigit(tem.charAt(j))) {
                tem2.append(tem.charAt(j));
            }
        }
        sommet1_txt.setText("" + tem2);
    }//GEN-LAST:event_sommet1_txtKeyReleased

    private void sommet2_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sommet2_txtKeyReleased
        String tem = new String(sommet2_txt.getText());
        StringBuffer tem2 = new StringBuffer();
        for (int j = 0; j < tem.length(); j++) {
            if (Character.isDigit(tem.charAt(j))) {
                tem2.append(tem.charAt(j));
            }
        }
        sommet2_txt.setText("" + tem2);
    }//GEN-LAST:event_sommet2_txtKeyReleased

    private void poids_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_poids_txtKeyReleased
        String tem = new String(poids_txt.getText());
        StringBuffer tem2 = new StringBuffer();
        for (int j = 0; j < tem.length(); j++) {
            if (Character.isDigit(tem.charAt(j))) {
                tem2.append(tem.charAt(j));
            }
        }
        poids_txt.setText("" + tem2);
    }//GEN-LAST:event_poids_txtKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frame1.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aréte_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aréte_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aréte_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aréte_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aréte_window().setVisible(true);
            }
        });
    }
    private int i = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton déssiner_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField poids_txt;
    private javax.swing.JTextField sommet1_txt;
    private javax.swing.JTextField sommet2_txt;
    // End of variables declaration//GEN-END:variables
}
