/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import Classes.Graphe;
import Classes.Paint;
import java.awt.Frame;
import javax.swing.JOptionPane;

public class Eliminer_Aréte extends javax.swing.JFrame {

    int i;

    private Eliminer_Aréte() {

    }

    public void R_repaint() {
        for (int j = 0; j < i; j++) {
            for (int k = 0; k < i; k++) {
                if (graphe.getMatrice_adjacence(j, k) == 1) {
                    Paint.Paint_Line(Principal_Window.graphe_panel.getGraphics(), graphe.getCordX(j), graphe.getCordY(j), graphe.getCordX(k), graphe.getCordY(k), graphe.getMatrice_Coefficients(j, k));
                }
            }
        }
        for (int j = 0; j < i; j++) {
            Paint.Paint_Cercle(Principal_Window.graphe_panel.getGraphics(), graphe.getCordX(j), graphe.getCordY(j), String.valueOf(graphe.getNombre(j)));

        }
    }

    Paint paint;
    Graphe graphe;
    Frame frame;

    public Eliminer_Aréte(Paint paint, Graphe graphe, int ii, Frame fram) {
        initComponents();
        i = ii;
        this.paint = paint;
        this.graphe = graphe;
        frame = fram;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eliminer_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Shortest Path");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(60, 109, 245));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminer Aréte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(60, 109, 245))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(60, 109, 245));
        jPanel2.setLayout(null);

        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        n1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                n1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                n1KeyReleased(evt);
            }
        });
        jPanel2.add(n1);
        n1.setBounds(140, 30, 30, 20);

        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        n2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                n2KeyReleased(evt);
            }
        });
        jPanel2.add(n2);
        n2.setBounds(140, 60, 30, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 109, 245));
        jLabel1.setText("Entrez le sommet 1:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 30, 120, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 109, 245));
        jLabel2.setText("Entrez le sommet 2:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 60, 120, 14);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 10, 180, 90);

        eliminer_btn.setBackground(new java.awt.Color(255, 255, 255));
        eliminer_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eliminer_btn.setForeground(new java.awt.Color(60, 109, 245));
        eliminer_btn.setText("Eliminer");
        eliminer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminer_btnActionPerformed(evt);
            }
        });
        jPanel1.add(eliminer_btn);
        eliminer_btn.setBounds(70, 110, 90, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void n1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1KeyPressed

    private void n1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n1KeyReleased
        String tem = new String(n1.getText());
        StringBuffer tem2 = new StringBuffer();
        for (int j = 0; j < tem.length(); j++) {
            if (Character.isDigit(tem.charAt(j))) {
                tem2.append(tem.charAt(j));
            }
        }
        n1.setText("" + tem2);
    }//GEN-LAST:event_n1KeyReleased

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n2ActionPerformed

    private void n2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_n2KeyReleased
        String tem = new String(n2.getText());
        StringBuffer tem2 = new StringBuffer();
        for (int j = 0; j < tem.length(); j++) {
            if (Character.isDigit(tem.charAt(j))) {
                tem2.append(tem.charAt(j));
            }
        }
        n2.setText("" + tem2);
    }//GEN-LAST:event_n2KeyReleased

    private void eliminer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminer_btnActionPerformed
        int x;
        int y;
        int taille;
        if (n1.getText().length() < 1 || n2.getText().length() < 1) {
            JOptionPane.showMessageDialog(null, "Erreur.. Données manquantes : ");
        } else {
            x = Integer.parseInt(n1.getText());
            y = Integer.parseInt(n2.getText());

            if (x == y) {
                JOptionPane.showMessageDialog(null, "Erreur.. Vous devez taper un autre sommet : " + y);
            } else if (x < 0 || x >= i || y < 0 || y >= i) {
                JOptionPane.showMessageDialog(null, "Erreur.. Sommet non valide ");
            } else {
                graphe.setMatrice_adjacence(x, y, 0);
                graphe.setMatrice_adjacence(y, x, 0);
                graphe.setMatrice_Coefficients(x, y, 0);
                graphe.setMatrice_Coefficients(y, x, 0);
                n1.setText(null);
                n2.setText(null);
                Principal_Window.graphe_panel.paint(Principal_Window.graphe_panel.getGraphics());

                R_repaint();

            }
        }
    }//GEN-LAST:event_eliminer_btnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frame.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminer_Aréte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminer_Aréte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminer_Aréte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminer_Aréte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminer_Aréte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminer_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    // End of variables declaration//GEN-END:variables
}
